export const partsCategoryOptions = [
  { value: "engineOilsAndFluids", label: "Engine Oils & Fluids" },
  { value: "carCare", label: "Car Care" },
  { value: "carAccessories", label: "Car Accessories" },
  { value: "carParts", label: "Car Parts" },
  { value: "brakesSuspensionAndSteering", label: "Brakes, Suspension & Steering" },
  { value: "headlightsLighting", label: "Headlights & Lighting" },
  { value: "batteries", label: "Batteries" },
  { value: "technologySafetySecurity", label: "Technology I Safety I Security" },
  { value: "tyres", label: "Tyres" },
  { value: "paintsBodyRepairs", label: "Paints & Body Repairs" },
  { value: "wheelsParts", label: "Wheels & Parts" },
  { value: "childSeats", label: "Child Seats" },
  { value: "camping", label: "Camping" },
  { value: "caravansMotorhomes", label: "Caravans & Motorhomes" },
  { value: "other", label: "Other" },
];

export const partsSubCategoryOptions = [
  { category: "engineOilsAndFluids", value: "ाngineOil", label: "Engine Oil" },
  { category: "engineOilsAndFluids", value: "motorsportOil", label: "Motorsport Oil" },
  { category: "engineOilsAndFluids", value: "adBlue", label: "AdBlue" },
  { category: "engineOilsAndFluids", value: "antiFreeze", label: "Anti-Freeze" },
  { category: "engineOilsAndFluids", value: "brakeClutchFluid", label: "Brake Clutch Fluid" },
  {
    category: "engineOilsAndFluids",
    value: "engineCleanerDegreaser",
    label: "Engine Cleaner & Degreaser",
  },
  { category: "engineOilsAndFluids", value: "Fuel & Oil Additives", label: "Fuel & Oil Additives" },
  { category: "engineOilsAndFluids", value: "Air Con", label: "Air Con" },
  { category: "engineOilsAndFluids", value: "Gearbox Oil", label: "Gearbox Oil" },
  { category: "engineOilsAndFluids", value: "Motor Oil", label: "Motor Oil" },
  { category: "engineOilsAndFluids", value: "Hydraulic Oil ", label: "Hydraulic Oil " },
  { category: "engineOilsAndFluids", value: "Unspecified", label: "Unspecified" },
  {
    category: "engineOilsAndFluids",
    value: "Lubricating & Penetrating Oil",
    label: "Lubricating & Penetrating Oil",
  },
  { category: "engineOilsAndFluids", value: "Power Steering Fluid", label: "Power Steering Fluid" },
  { category: "engineOilsAndFluids", value: "DPF Cleaner", label: "DPF Cleaner" },
  { category: "engineOilsAndFluids", value: "Transmission Oil", label: "Transmission Oil" },
  { category: "engineOilsAndFluids", value: "Suspension Fluid", label: "Suspension Fluid" },
  { category: "engineOilsAndFluids", value: "Classic Car Oil", label: "Classic Car Oil" },
  { category: "engineOilsAndFluids", value: "Unspecified", label: "Unspecified" },
];
