export const myArr = [
  {
    "Aerial Platforms": "Articulated Platforms",
    Attachments: "Other",
    "Buildings & Storage": "Buildings",
    "Compaction Machines": "Double Drum",
    Compressors: "Static",
    Concrete: "Bathing & Solis",
    "Conveyor Belts": "Other",
    Cranes: "Crawler Cranes",
    Dozers: "Tracked Dozers",
    Dumpers: "Articulated Dump Trucks",
    Excavators: "Attachments",
    Forklifts: "Terrain Forklifts",
    Generators: "Static",
    Graders: "Other",
    Loaders: "Backhoe Loaders",
    "Mining & Quarry Equipment": "Other",
    "Road & Paving Machine": "Other",
    "Road Construction Machine": "Other",
    Scrappers: "Other",
    Telehandlers: "Other",
    "Tools & Equipment": "Lifting Euipment",
    Trailers: "Attachments",
    "Waster & Recycling": "Skips",
  },
  {
    "Aerial Platforms": "Scissors",
    "Buildings & Storage": "Tanks",
    "Compaction Machines": "Plate Compactor",
    Compressors: "Trailer",
    Concrete: "Mixer",
    Cranes: "Truck Mounted Cranes",
    Dozers: "Others",
    Dumpers: "Dump Trucks",
    Excavators: "Mirco Excavators",
    Forklifts: "Attachments",
    Generators: "Trailer",
    Loaders: "Front Shovels",
    "Tools & Equipment": "Other",
    Trailers: "Flatbed",
    "Waster & Recycling": "Sweepers",
  },
  {
    "Aerial Platforms": "Telescopic Platforms",
    "Buildings & Storage": "Water & Fuel Bowers",
    "Compaction Machines": "Single Drum Smooth",
    Concrete: "Pumps",
    Cranes: "Other",
    Dumpers: "Mini Dumpers",
    Excavators: "Mini Excavators",
    Forklifts: "Container Handlers",
    Loaders: "Skid Steer Loaders",
    Trailers: "General Purpose",
    "Waster & Recycling": "Wood Chippers",
  },
  {
    "Buildings & Storage": "Welfare Units",
    "Compaction Machines": "Trench",
    Dumpers: "Skip Dumpers",
    Excavators: "Truck Excavators",
    Forklifts: "Counter Balance Forklifts",
    Loaders: "Track Loaders",
    Trailers: "Low Loader",
    "Waster & Recycling": "Other",
  },
  {
    "Buildings & Storage": "Other",
    "Compaction Machines": "Other",
    Dumpers: "Track Dumpers",
    Excavators: "Wheeled Excavators",
    Forklifts: "Narrow Aisle Trucks",
    Loaders: "Wheeled Loaders",
    Trailers: "Tipping ",
  },
  {
    Forklifts: "Pedestrian Stackers",
    Loaders: "Other",
    Trailers: "Other",
  },
  {
    Forklifts: "Reach Trucks",
  },
  {
    Forklifts: "Side Loaders",
  },
];
